// Maria Eduarda
package view;

import conexao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class CadastroView extends javax.swing.JFrame {
    
    /**
     * Creates new form CadastroView
     */
    public CadastroView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        nometxt = new javax.swing.JTextField();
        cadastrarbnt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        voltarmenutxt = new javax.swing.JButton();
        showHideToggleButton = new javax.swing.JToggleButton();
        senhatxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cadastro de usuário");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 240, -1));

        nometxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nometxtActionPerformed(evt);
            }
        });
        getContentPane().add(nometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 240, -1));

        cadastrarbnt.setText("Cadastrar");
        cadastrarbnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarbntActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrarbnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 190, 60));

        jLabel2.setText("Senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 20));

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 20));

        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, 20));

        voltarmenutxt.setText("Voltar para o Menu");
        voltarmenutxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarmenutxtActionPerformed(evt);
            }
        });
        getContentPane().add(voltarmenutxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        showHideToggleButton.setText("( ͡° ͜ʖ ͡°)");
        showHideToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHideToggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(showHideToggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        senhatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhatxtActionPerformed(evt);
            }
        });
        getContentPane().add(senhatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nometxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nometxtActionPerformed

    private void cadastrarbntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarbntActionPerformed
        // TODO add your handling code here:
        cadastrarUsuario();
    }//GEN-LAST:event_cadastrarbntActionPerformed

    private void voltarmenutxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarmenutxtActionPerformed
        // TODO add your handling code here:
        //Volta para o menu principal
        Menu1 obj = new Menu1();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltarmenutxtActionPerformed

    private void showHideToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideToggleButtonActionPerformed
        // TODO add your handling code here:
        if (showHideToggleButton.isSelected()) {
            senhatxt.setEchoChar((char) 0); // Mostra a senha
        } else {
            senhatxt.setEchoChar('\u2022'); // Oculta a senha 
        }
    }//GEN-LAST:event_showHideToggleButtonActionPerformed

    private void senhatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhatxtActionPerformed

    //Cadastrar novo usuário no banco de dados
    private void cadastrarUsuario() {
        String nome = nometxt.getText();
        String email = emailtxt.getText();
        String senha = senhatxt.getText();

        try (Connection conexao = Conexao.getInstance()) {
            String query = "INSERT INTO usuarios (nome, email, senha) VALUES (?, ?, ?)";
            try (PreparedStatement pst = conexao.prepareStatement(query)) {
                pst.setString(1, nome);
                pst.setString(2, email);
                pst.setString(3, senha);

                int rowsAffected = pst.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário. Tente novamente.");
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de banco de dados. Tente novamente.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroView obj = new CadastroView();
                obj.setLocationRelativeTo(obj);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarbnt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nometxt;
    private javax.swing.JPasswordField senhatxt;
    private javax.swing.JToggleButton showHideToggleButton;
    private javax.swing.JButton voltarmenutxt;
    // End of variables declaration//GEN-END:variables
}
