// Arthur Segheto, Gabrielle Fonseca, Maria Eduarda e Pedro Arthur
package view;

import conexao.Conexao;
import dao.CarteiraDAO;
import observer.CarteiraLogger;
import entity.Carteira;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrameApp extends javax.swing.JFrame {

    private Conexao conexao;
    private Connection conn;
    private CarteiraDAO carteiraDAO;

    //Atualiza os valores de ganho, gasto e diferença na interface
    private void atualizarValoresNaTela() {
        CarteiraDAO valores = new CarteiraDAO();

        if (!valores.isVazio()) {
            CarteiraDAO carteiraDAO = new CarteiraDAO();
            double totalGanhos = carteiraDAO.calcularTotalGanhos(); //chamando método que calcula o total de ganhos
            double totalGastos = carteiraDAO.calcularTotalGastos(); //chamando método que calcula o total de gastos
            double diferenca = totalGanhos - totalGastos; //Fazendo o claculo da diferença

            //Atualizando os jLabel com os valores
            recebidoTxt.setText(String.format("%.2f", totalGanhos));
            gastoTxt.setText(String.format("%.2f", totalGastos));
            diferencaTxt.setText(String.format("%.2f", diferenca));
            recebidoTxt.setVisible(true);
            jLabel5.setVisible(true);
            gastoTxt.setVisible(true);
            jLabel7.setVisible(true);
            diferencaTxt.setVisible(true);
            jLabel9.setVisible(true);
        } else {
            // Esconde campos de soma e diferença
            recebidoTxt.setVisible(false);
            jLabel5.setVisible(false);
            gastoTxt.setVisible(false);
            jLabel7.setVisible(false);
            diferencaTxt.setVisible(false);
            jLabel9.setVisible(false);

            // Mostra mensagem
            JOptionPane.showMessageDialog(this, "Não há entradas cadastradas até o momento.");
        }
    }

    //Chama o metodo listarCarteira() apara ser usado na interface e lista os valores
    public void Listar() {
        try {
            CarteiraDAO carteiraDAO = new CarteiraDAO();

            // Adiciona um observador
            CarteiraLogger carteiraLogger = new CarteiraLogger();
            carteiraDAO.addObserver(carteiraLogger);

            List<Carteira> carteira = carteiraDAO.listarCarteira();

            DefaultTableModel model = (DefaultTableModel) entradasTabela.getModel();
            model.setNumRows(0);

            for (Carteira c : carteira) {
                model.addRow(new Object[]{
                    c.getId(),
                    c.getNome(),
                    c.getClassificacao(),
                    c.getValor(),
                    c.getRealDate(),
                    c.getData()
                });
            }
        } catch (Exception e) {
        }
    }

    public FrameApp() {
        this.conexao = new Conexao();
        this.conn = this.conexao.getInstance();
        initComponents();
        carteiraDAO = new CarteiraDAO();
        Listar();
        atualizarValoresNaTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        classificacaoTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorTxt = new javax.swing.JTextField();
        jtID = new javax.swing.JLabel();
        dataTxt = new javax.swing.JFormattedTextField();
        cadastrarBtn = new javax.swing.JButton();
        ganhoBtn = new javax.swing.JRadioButton();
        gastoBtn = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradasTabela = new javax.swing.JTable();
        deletarBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        recebidoTxt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gastoTxt = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        diferencaTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        refreshBtn1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        nomeTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Classificação");

        classificacaoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        classificacaoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classificacaoTxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Valor");

        valorTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valorTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorTxtActionPerformed(evt);
            }
        });

        jtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtID.setText("ID: AutoIncrement");

        try {
            dataTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTxtActionPerformed(evt);
            }
        });

        cadastrarBtn.setBackground(new java.awt.Color(255, 153, 153));
        cadastrarBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadastrarBtn.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarBtn.setText("CADASTRAR");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        ganhoBtn.setBackground(new java.awt.Color(153, 204, 255));
        ganhoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ganhoBtn.setForeground(new java.awt.Color(0, 204, 51));
        ganhoBtn.setText("Ganho (+)");
        ganhoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ganhoBtnMouseClicked(evt);
            }
        });
        ganhoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ganhoBtnActionPerformed(evt);
            }
        });

        gastoBtn.setBackground(new java.awt.Color(153, 204, 255));
        gastoBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gastoBtn.setForeground(new java.awt.Color(255, 0, 51));
        gastoBtn.setText("Gasto (-)");
        gastoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastoBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtID))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(nomeTxt)
                            .addComponent(classificacaoTxt)
                            .addComponent(valorTxt))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gastoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ganhoBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(nomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(classificacaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(valorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtID))
                .addGap(42, 42, 42)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ganhoBtn)
                .addGap(15, 15, 15)
                .addComponent(gastoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cadastrarBtn)
                .addGap(35, 35, 35))
        );

        entradasTabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entradasTabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        entradasTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Classificação", "Valor", "Data Entrada", "Data Cadastrada"
            }
        ));
        entradasTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entradasTabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(entradasTabela);

        deletarBtn.setText("DEL");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Recebido (R$):");

        recebidoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recebidoTxt.setText("0.00");
        recebidoTxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                recebidoTxtComponentShown(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gastos (R$):");

        gastoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gastoTxt.setText("0.00");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Diferença (R$):");

        diferencaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diferencaTxt.setText("0.00");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Finanças Anuais");

        refreshBtn1.setText("Refresh");
        refreshBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtn1ActionPerformed(evt);
            }
        });

        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recebidoTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gastoTxt)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diferencaTxt)
                        .addGap(70, 70, 70)
                        .addComponent(refreshBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(464, 464, 464)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit)
                    .addComponent(Voltar)
                    .addComponent(jLabel5)
                    .addComponent(recebidoTxt)
                    .addComponent(jLabel7)
                    .addComponent(gastoTxt)
                    .addComponent(jLabel9)
                    .addComponent(diferencaTxt)
                    .addComponent(refreshBtn1)
                    .addComponent(deletarBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ganhoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ganhoBtnActionPerformed

    }//GEN-LAST:event_ganhoBtnActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        //Cadastra os valores no BD e insere na jTable
        String nome = nomeTxt.getText();
        String classificacao = classificacaoTxt.getText();
        Double valor = Double.valueOf(valorTxt.getText());
        String data = dataTxt.getText();

        if (gastoBtn.isSelected()) {
            valor *= -1; // Faz o valor ficar negativo pras despesas totais serem calculadas
        }

        Carteira carteira = new Carteira();
        carteira.setNome(nome);
        carteira.setClassificacao(classificacao);
        carteira.setValor(valor);
        carteira.setData(data);

        CarteiraDAO clienteDAO = new CarteiraDAO();
        clienteDAO.inserir(carteira);

        nomeTxt.setText("");
        classificacaoTxt.setText("");
        valorTxt.setText("");
        dataTxt.setText("");

        Listar();
        atualizarValoresNaTela();
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void nomeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTxtActionPerformed

    private void classificacaoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classificacaoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classificacaoTxtActionPerformed

    private void valorTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorTxtActionPerformed

    private void dataTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTxtActionPerformed

    private void gastoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastoBtnActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        //Deleta os valores que forem selecionados na tabela tanto na jTable/BD
        try {
            Carteira carteira = new Carteira();
            carteira.setId(Integer.parseInt(jtID.getText()));

            CarteiraDAO dao = new CarteiraDAO();

            int input = JOptionPane.showConfirmDialog(null,
                    "Tem certeza de que deseja excluir?", "Selecione uma opção...", JOptionPane.YES_NO_CANCEL_OPTION);

            if (input == 0) {
                dao.excluir(carteira);
                JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Operação cancelada.");
            }

            Listar();

            nomeTxt.setText("");
            classificacaoTxt.setText("");
            valorTxt.setText("");
            dataTxt.setText("");

            Listar();
            atualizarValoresNaTela();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir os dados.");
        }
    }//GEN-LAST:event_deletarBtnActionPerformed

    private void refreshBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtn1ActionPerformed
        //Lista os valores - atualiza a tabela 
        Listar();
        atualizarValoresNaTela();
    }//GEN-LAST:event_refreshBtn1ActionPerformed

    private void entradasTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entradasTabelaMouseClicked
        //Quando uma linha na tabela é selecionada, automaticamente os de texto são completados com os valores selecionados
        jtID.setText(entradasTabela.getValueAt(entradasTabela.getSelectedRow(), 0).toString());
        nomeTxt.setText(entradasTabela.getValueAt(entradasTabela.getSelectedRow(), 1).toString());
        classificacaoTxt.setText(entradasTabela.getValueAt(entradasTabela.getSelectedRow(), 2).toString());
        valorTxt.setText(entradasTabela.getValueAt(entradasTabela.getSelectedRow(), 3).toString());
        dataTxt.setText(entradasTabela.getValueAt(entradasTabela.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_entradasTabelaMouseClicked

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //Pergunta se o usuário realmente deseja sair e se a resposta for "sim" o programa fecha e a conexão com o banco é interrompida
        int input = JOptionPane.showConfirmDialog(null,
                "Tem certeza de que deseja sair?", "Selecione uma opção...", JOptionPane.YES_NO_CANCEL_OPTION);

        if (input == 0) {
            JOptionPane.showMessageDialog(null, "Até a próxima :)");
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada.");
        }
    }//GEN-LAST:event_exitActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        //Volta para o menu principal
        Menu1 obj = new Menu1();
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void ganhoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ganhoBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ganhoBtnMouseClicked

    private void recebidoTxtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_recebidoTxtComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_recebidoTxtComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameApp obj = new FrameApp();
                obj.setLocationRelativeTo(obj);
                obj.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JTextField classificacaoTxt;
    private javax.swing.JFormattedTextField dataTxt;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JLabel diferencaTxt;
    private javax.swing.JTable entradasTabela;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton ganhoBtn;
    private javax.swing.JRadioButton gastoBtn;
    private javax.swing.JLabel gastoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jtID;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JLabel recebidoTxt;
    private javax.swing.JButton refreshBtn1;
    private javax.swing.JTextField valorTxt;
    // End of variables declaration//GEN-END:variables
}
